### ISSUE TITLE
Some github emoji for you

### ISSUE THREAD

**Issue by blade254353074** [shinux/shinux.github.io#1]
:feelsgood: :finnadie: :goberserk: :godmode: :octocat: :rage1: :rage2: :rage3: :rage4: :shipit: :trollface:

**Comment by shinux** [comment]
🌊

**Comment by blade254353074** [comment]
:rage1: :rage2: :rage3: :rage4: :feelsgood: :finnadie: :goberserk: :godmode:

:trollface:

:shipit:

:octocat:
